const ACTIONS_TYPES = {
    PRODUCT: {
        GET_PRODUCT_CATEGORY_START: 'GET_PRODUCT_CATEGORY_START',
        GET_PRODUCT_CATEGORY_FAILED: 'GET_PRODUCT_CATEGORY_FAILED',
        GET_PRODUCT_CATEGORY_SUCCESS: 'GET_PRODUCT_CATEGORY_SUCCESS',

    }
}

export default ACTIONS_TYPES