const ACTIONS_TYPES = {
    PRODUCT: {
        GET_PRODUCT_CATEGORY_START: 'GET_PRODUCT_CATEGORY_START',
        GET_PRODUCT_CATEGORY_FAILED: 'GET_PRODUCT_CATEGORY_FAILED',
        GET_PRODUCT_CATEGORY_SUCCESS: 'GET_PRODUCT_CATEGORY_SUCCESS',
        GET_LIST_PRODUCT_START: 'GET_LIST_PRODUCT_START',
        GET_LIST_PRODUCT_FAILED: 'GET_LIST_PRODUCT_FAILED',
        GET_LIST_PRODUCT_SUCCESS: 'GET_LIST_PRODUCT_SUCCESS',
        GET_TOP_PRODUCT_START: 'GET_TOP_PRODUCT_START',
        GET_TOP_PRODUCT_FAILED: 'GET_TOP_PRODUCT_FAILED',
        GET_TOP_PRODUCT_SUCCESS: 'GET_TOP_PRODUCT_SUCCESS',
    },
    REVIEW: {
        GET_ALL_REVIEW_START: 'GET_ALL_REVIEW_START',
        GET_ALL_REVIEW_FAILED: 'GET_ALL_REVIEW_FAILED',
        GET_ALL_REVIEW_SUCCESS: 'GET_ALL_REVIEW_SUCCESS',
    },
    FEED: {
        GET_ALL_FEED_START: 'GET_ALL_FEED_START',
        GET_ALL_FEED_FAILED: 'GET_ALL_FEED_FAILED',
        GET_ALL_FEED_SUCCESS: 'GET_ALL_FEED_SUCCESS',
    },
    EVENT:{
        GET_DATA_EVENT_START: 'GET_DATA_EVENT_START',
        GET_DATA_EVENT_FAILED: 'GET_DATA_EVENT_FAILED',
        GET_DATA_EVENT_SUCCESS: 'GET_DATA_EVENT_SUCCESS',
        GET_DATA_COMMENT_START: 'GET_DATA_COMMENT_START',
        GET_DATA_COMMENT_FAILED: 'GET_DATA_COMMENT_FAILED',
        GET_DATA_COMMENT_SUCCESS: 'GET_DATA_COMMENT_SUCCESS',
    }
}

export default ACTIONS_TYPES