const ACTIONS_TYPES = {
    PRODUCT: {
        GET_PRODUCT_CATEGORY_START: 'GET_PRODUCT_CATEGORY_START',
        GET_PRODUCT_CATEGORY_FAILED: 'GET_PRODUCT_CATEGORY_FAILED',
        GET_PRODUCT_CATEGORY_SUCCESS: 'GET_PRODUCT_CATEGORY_SUCCESS',
        GET_LIST_PRODUCT_START: 'GET_LIST_PRODUCT_START',
        GET_LIST_PRODUCT_FAILED: 'GET_LIST_PRODUCT_FAILED',
        GET_LIST_PRODUCT_SUCCESS: 'GET_LIST_PRODUCT_SUCCESS',
    },
    EVENT:{
        GET_DATA_EVENT_START: 'GET_DATA_EVENT_START',
        GET_DATA_EVENT_FAILED: 'GET_DATA_EVENT_FAILED',
        GET_DATA_EVENT_SUCCESS: 'GET_DATA_EVENT_SUCCESS',
    }
}

export default ACTIONS_TYPES